add feature repeat given column when split across pages
simonbengtsson/jsPDF-AutoTable pull request #801
Opened 2021-05-12 20:52 UTC by singhinderpal

just pass the data key to repeat in config
`horizontalPageBreakRepeat: 'id'`

2021-05-12 20:55 UTC, singhinderpal commented
#800 Linking to the issue.

2021-05-13 21:37 UTC, simonbengtsson commented
Looks great! Had some minor comments. Also, does this support specifying a column index instead of a key? For example 

`horizontalPageBreakRepeat: 0`

2021-05-13 21:37 UTC, simonbengtsson requested changes

2021-05-13 21:37 UTC, simonbengtsson commented on src/tablePrinter.ts
> +  let repeatColumnIndex = -1;
I think we can simplify some code here if we remove the repeatColumnIndex in favour of moving `repeatCol` outside of the if statement. Something like this:

```
const repeatColumn = null
if (horizontalPageBreakRepeat) {
    repeatColumn = table.columns.find((item) => item.dataKey == horizontalPageBreakRepeat);
    // ...
  }
  while (i < len) {
    if (repeatColumn?.index === i) {
    // ...
```

2021-05-14 10:08 UTC, singhinderpal commented
Hello @simonbengtsson 

The changed have been done and support to consume indexes in horizontalPageBreakRepeat is also added. Kindly review.

2021-05-14 10:12 UTC, simonbengtsson commented
Looks great! Two things left:
- Run prettier on it to format it like the rest of the code
- Add documentation

2021-05-14 17:33 UTC, singhinderpal commented
Hello @simonbengtsson 

I have added an example for horizontalPageBreakRepeat and ran prettier to format the code,

I request you to review and merge.

2021-05-15 18:32 UTC, simonbengtsson commented
No need for an example, but would be great if the option would be described in the documentation (ie README.md).

2021-05-15 19:54 UTC, singhinderpal commented
Hi @simonbengtsson 
Its now added under Other options section.

2021-05-16 08:14 UTC, simonbengtsson commented
Looks great!

2021-05-16 08:14 UTC, merged